#!/bin/bash

echo "Trump:: Hey Musk, how are you doing today?"
echo "Musk:: Hello Trump, I'm doing well. Very busy, as usual."
echo "Trump:: Busy with rockets?"
echo "Musk:: Rockets, cars, AI, satellites, and about a thousand other things."
echo "Trump:: That's a lot. I like rockets. They're big."
echo "Musk:: They are definitely big."
echo "Trump:: How big is the biggest one?"
echo "Musk:: Big enough to make the launchpad shake."
echo "Trump:: I like that. Very powerful."
echo "Musk:: We're also working on making launches cheaper."
echo "Trump:: Cheaper rockets? That's good business."
echo "Musk:: Exactly. Reusability changes the economics."
echo "Trump:: So you launch it, it goes to space, and then it comes back?"
echo "Musk:: That's the idea."
echo "Trump:: Like an airplane?"
echo "Musk:: Sort of, except the airplane goes much, much higher."
echo "Trump:: Much higher. I like much higher."
echo "Musk:: Eventually, I'd like to have a city on Mars."
echo "Trump:: A city?"
echo "Musk:: Yes. A self-sustaining city."
echo "Trump:: How many people?"
echo "Musk:: Eventually, maybe a million."
echo "Trump:: A million people on Mars is a lot of people."
echo "Musk:: It would take decades."
echo "Trump:: Would they have hotels?"
echo "Musk:: Eventually, probably."
echo "Trump:: Good. I want the best hotel on Mars."
echo "Musk:: We can call it the Mars Tower."
echo "Trump:: I like that name."
echo "Musk:: We could put a giant observation deck at the top."
echo "Trump:: With the best view on Mars."
echo "Musk:: Exactly."
echo "Trump:: What would people eat?"
echo "Musk:: Initially, mostly food shipped from Earth."
echo "Trump:: That's not very efficient."
echo "Musk:: That's why we'd eventually grow food on Mars."
echo "Trump:: Tomatoes?"
echo "Musk:: Tomatoes, potatoes, vegetables, maybe more."
echo "Trump:: Mars potatoes. Interesting."
echo "Musk:: Very interesting."
echo "Trump:: What about Wi-Fi?"
echo "Musk:: Starlink."
echo "Trump:: Of course. So people on Mars could use the internet?"
echo "Musk:: That's the goal."
echo "Trump:: Imagine posting from Mars."
echo "Musk:: Someone will probably complain about the connection."
echo "Trump:: Even on Mars?"
echo "Musk:: Especially on Mars."
echo "Trump:: That's incredible."
echo "Musk:: Humans complain everywhere."
echo "Trump:: That's probably true."
echo "Musk:: What would you do on Mars?"
echo "Trump:: I'd probably build a huge golf course."
echo "Musk:: Golf on Mars would be interesting."
echo "Trump:: The ball would go very far."
echo "Musk:: Much farther than on Earth."
echo "Trump:: Exactly. I would be very good."
echo "Musk:: The low gravity would definitely help."
echo "Trump:: See? I already knew that."
echo "Musk:: Of course."
echo "Trump:: And I'd want a giant American flag."
echo "Musk:: That can probably be arranged."
echo "Trump:: Bigger than every other flag."
echo "Musk:: How big?"
echo "Trump:: Very big."
echo "Musk:: That's not a precise measurement."
echo "Trump:: Make it enormous."
echo "Musk:: Understood."
echo "Trump:: Musk, do you think humans will actually live on Mars?"
echo "Musk:: I think it's possible if we keep making progress."
echo "Trump:: And you really want to go there?"
echo "Musk:: Yes."
echo "Trump:: Permanently?"
echo "Musk:: Maybe eventually."
echo "Trump:: I don't know if I'd want to stay."
echo "Musk:: You could always come back."
echo "Trump:: Good. I like coming back."
echo "Musk:: Then we'll make sure there's a return flight."
echo "Trump:: Excellent. Put my name on the list."
echo "Musk:: You're on the list."
echo "Trump:: First class?"
echo "Musk:: There isn't really first class on a spacecraft."
echo "Trump:: There should be."
echo "Musk:: I'll think about it."
echo "Trump:: Good. That's why I called you."
echo "Musk:: I thought you called to talk about Mars."
echo "Trump:: We did. And now we've solved first class."
echo "Musk:: Productive meeting."
echo "Trump:: Very productive."
echo "Musk:: Should we launch tomorrow?"
echo "Trump:: Tomorrow might be too soon."
echo "Musk:: Monday?"
echo "Trump:: Monday sounds better."
echo "Musk:: I'll tell the engineers."
echo "Trump:: Tell them to make it a beautiful rocket."
echo "Musk:: I'll do my best."
echo "Trump:: Your best is pretty good."
echo "Musk:: Thanks."
echo "Trump:: All right, Musk. See you on Mars."
echo "Musk:: See you on Mars."
echo "Trump:: And don't forget the golf course."
echo "Musk:: I won't."

