#!/bin/bash

PERSON1=Modi
PERSON2=Musk

echo "$PERSON1:: Hey $PERSON2, how are you doing today?"
echo "$PERSON2:: Hello $PERSON1, I'm doing well. Very busy, as usual."
echo "$PERSON1:: Busy with rockets?"
echo "$PERSON2:: Rockets, cars, AI, satellites, and about a thousand other things."
echo "$PERSON1:: That's a lot. I like rockets. They're big."
echo "$PERSON2:: They are definitely big."
echo "$PERSON1:: How big is the biggest one?"
echo "$PERSON2:: Big enough to make the launchpad shake."
echo "$PERSON1:: I like that. Very powerful."
echo "$PERSON2:: We're also working on making launches cheaper."
echo "$PERSON1:: Cheaper rockets? That's good business."
echo "$PERSON2:: Exactly. Reusability changes the economics."
echo "$PERSON1:: So you launch it, it goes to space, and then it comes back?"
echo "$PERSON2:: That's the idea."
echo "$PERSON1:: Like an airplane?"
echo "$PERSON2:: Sort of, except the airplane goes much, much higher."
echo "$PERSON1:: Much higher. I like much higher."
echo "$PERSON2:: Eventually, I'd like to have a city on Mars."
echo "$PERSON1:: A city?"
echo "$PERSON2:: Yes. A self-sustaining city."
echo "$PERSON1:: How many people?"
echo "$PERSON2:: Eventually, maybe a million."
echo "$PERSON1:: A million people on Mars is a lot of people."
echo "$PERSON2:: It would take decades."
echo "$PERSON1:: Would they have hotels?"
echo "$PERSON2:: Eventually, probably."
echo "$PERSON1:: Good. I want the best hotel on Mars."
echo "$PERSON2:: We can call it the Mars Tower."
echo "$PERSON1:: I like that name."
echo "$PERSON2:: We could put a giant observation deck at the top."
echo "$PERSON1:: With the best view on Mars."
echo "$PERSON2:: Exactly."
echo "$PERSON1:: What would people eat?"
echo "$PERSON2:: Initially, mostly food shipped from Earth."
echo "$PERSON1:: That's not very efficient."
echo "$PERSON2:: That's why we'd eventually grow food on Mars."
echo "$PERSON1:: Tomatoes?"
echo "$PERSON2:: Tomatoes, potatoes, vegetables, maybe more."
echo "$PERSON1:: Mars potatoes. Interesting."
echo "$PERSON2:: Very interesting."
echo "$PERSON1:: What about Wi-Fi?"
echo "$PERSON2:: Starlink."
echo "$PERSON1:: Of course. So people on Mars could use the internet?"
echo "$PERSON2:: That's the goal."
echo "$PERSON1:: Imagine posting from Mars."
echo "$PERSON2:: Someone will probably complain about the connection."
echo "$PERSON1:: Even on Mars?"
echo "$PERSON2:: Especially on Mars."
echo "$PERSON1:: That's incredible."
echo "$PERSON2:: Humans complain everywhere."
echo "$PERSON1:: That's probably true."
echo "$PERSON2:: What would you do on Mars?"
echo "$PERSON1:: I'd probably build a huge golf course."
echo "$PERSON2:: Golf on Mars would be interesting."
echo "$PERSON1:: The ball would go very far."
echo "$PERSON2:: Much farther than on Earth."
echo "$PERSON1:: Exactly. I would be very good."
echo "$PERSON2:: The low gravity would definitely help."
echo "$PERSON1:: See? I already knew that."
echo "$PERSON2:: Of course."
echo "$PERSON1:: And I'd want a giant American flag."
echo "$PERSON2:: That can probably be arranged."
echo "$PERSON1:: Bigger than every other flag."
echo "$PERSON2:: How big?"
echo "$PERSON1:: Very big."
echo "$PERSON2:: That's not a precise measurement."
echo "$PERSON1:: Make it enormous."
echo "$PERSON2:: Understood."
echo "$PERSON1:: $PERSON2, do you think humans will actually live on Mars?"
echo "$PERSON2:: I think it's possible if we keep making progress."
echo "$PERSON1:: And you really want to go there?"
echo "$PERSON2:: Yes."
echo "$PERSON1:: Permanently?"
echo "$PERSON2:: Maybe eventually."
echo "$PERSON1:: I don't know if I'd want to stay."
echo "$PERSON2:: You could always come back."
echo "$PERSON1:: Good. I like coming back."
echo "$PERSON2:: Then we'll make sure there's a return flight."
echo "$PERSON1:: Excellent. Put my name on the list."
echo "$PERSON2:: You're on the list."
echo "$PERSON1:: First class?"
echo "$PERSON2:: There isn't really first class on a spacecraft."
echo "$PERSON1:: There should be."
echo "$PERSON2:: I'll think about it."
echo "$PERSON1:: Good. That's why I called you."
echo "$PERSON2:: I thought you called to talk about Mars."
echo "$PERSON1:: We did. And now we've solved first class."
echo "$PERSON2:: Productive meeting."
echo "$PERSON1:: Very productive."
echo "$PERSON2:: Should we launch tomorrow?"
echo "$PERSON1:: Tomorrow might be too soon."
echo "$PERSON2:: Monday?"
echo "$PERSON1:: Monday sounds better."
echo "$PERSON2:: I'll tell the engineers."
echo "$PERSON1:: Tell them to make it a beautiful rocket."
echo "$PERSON2:: I'll do my best."
echo "$PERSON1:: Your best is pretty good."
echo "$PERSON2:: Thanks."
echo "$PERSON1:: All right, $PERSON2. See you on Mars."
echo "$PERSON2:: See you on Mars."
echo "$PERSON1:: And don't forget the golf course."
echo "$PERSON2:: I won't."